### ISSUE TITLE
Create loot-ui

### ISSUE THREAD

**Issue by joakin** [joakin/loot#12]
- [x] New repo
- [x] Set up deployment
- [x] Implement UI urls:
  - [x] Html page template
  - [x] Minimal CSS
    - Article styles: https://github.com/joakin/webkipedia/blob/master/src/webkipedia/ui/less/parsoid_page.less
    - Typography
    - Basic reset
  - [x] /wiki/:title
    - Chrome + slim
  - [x] /wiki/full/:title
    - Chrome + full
  - [x] Read more link

**Comment by phuedx** [comment]
Typography: https://github.com/wikimedia/mediawiki-extensions-MobileFrontend/blob/master/minerva.less/minerva.variables.less#L63-L72

**Comment by joakin** [comment]
See:
- Repo for the server: https://github.com/joakin/loot-ui
- Deployed version
  - Short fast version: http://reading-web-research.wmflabs.org/wiki/Donkey
  - Full article (click on Read more at the botton): http://reading-web-research.wmflabs.org/wiki/full/Donkey
