### ISSUE TITLE
Transform img to links with the img data

### ISSUE THREAD

**Issue by joakin** [joakin/loot#13]
https://etherpad.wikimedia.org/p/loot-plan

Link should point to full image.
Embed image attributes in `data-` attributes.

**Comment by joakin** [comment]
Easiest way is transform `img` into a `span` tag, and write inside the `resource` attr:

From:

``` html
<img resource="./File:Tossal-plantagral.jpg"
  src="//upload.wikimedia.org/wikipedia/commons/thumb/1/17/Tossal-plantagral.jpg/220px-Tossal-plantagral.jpg"
  data-file-width="756"
  data-file-height="504"
  data-file-type="bitmap"
  height="147" width="220" 
  id="mwLg"/>
```

To:

``` html
<span resource="./File:Tossal-plantagral.jpg"
  src="//upload.wikimedia.org/wikipedia/commons/thumb/1/17/Tossal-plantagral.jpg/220px-Tossal-plantagral.jpg"
  data-file-width="756"
  data-file-height="504"
  data-file-type="bitmap"
  height="147"
  width="220"
  id="mwLg">File:Tossal-plantagral.jpg</span>
```

**Comment by phuedx** [comment]
After reading through the [MediaWiki DOM spec](https://www.mediawiki.org/wiki/Parsoid/MediaWiki_DOM_spec#Images), I'm somewhat convinced that you're right. This is going to have be a lot more nuanced when **loot** is only returning JSON.
