### ISSUE TITLE
Remove conflictive inline styles

### ISSUE THREAD

**Issue by joakin** [joakin/loot#14]
Clean up style attrs css rules:
- whitespace: nowrap
- width: XXX

**Comment by phuedx** [comment]
Actually, I think that we could get rid of all inline styles.

**Comment by joakin** [comment]
Fixed by https://github.com/joakin/loot-ui/commit/68fb8f6ffd444fdf9ac8ecb7cf1d73df663b3a1c using CSS overrides as MF and discussed on irc.
