### ISSUE TITLE
Create slim/lead endpoint

### ISSUE THREAD

**Issue by joakin** [joakin/loot#18]
~~`/api/slim/lead/:title`~~ `/slim/lead/:title`
- [x] Infobox
- [x] Lead section
- [ ] References (only lead)

**Comment by phuedx** [comment]
Requires #17.

**Comment by phuedx** [comment]
I've updated the route to `/slim/lead/:title` per bb8ef39.

**Comment by phuedx** [comment]
I've removed the _With a "Read more..." button_ requirement as that's relevant to [loot-ui](https://github.com/joakin/loot-ui).

**Comment by phuedx** [comment]
The _References (only lead)_ requirement is tracked in #17.
