### ISSUE TITLE
Add endpoint for search

### ISSUE THREAD

**Issue by joakin** [joakin/loot#30]
`/search/:query`

Response, something like:

``` json
{
    "size": 10,
    "offset": 10,
    "total": 400,
    "items": [
        { "title": "adsf" }
    ]
}
```

Lets KISS for now, we'll add description, & thumbnails as we need them in the future.

This should proxy to MW api, maybe using the prefix search for now.

**Comment by joakin** [comment]
Above response is inspiration, structure as you please.

**Comment by joakin** [comment]
Why?

So that we can encapsulate the best way to search under the middleman server.

The strategy (prefixsearch, fullsearch, etc) should be transparent to the client.

**Comment by phuedx** [comment]
The `api` label is moot as **loot** is an API server now.

**Comment by joakin** [comment]
Fixed with https://github.com/joakin/loot/pull/37
